---
- name: Create Linux users using AWX
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars:
    users:
      - rahul.datta
      - seema.datta

  tasks:
    - name: Ensure users are present
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"
