---
- name: Create linux users
  hosts: all
  become: yes
  vars:
    users:
      - rahul.datta
      - seema.datta

  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"
